language: node_js


node_js:
  - 10.8

# after_success:
#   - npm run codecov
cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn install --ignore-engines
  
script:
  - yarn run lint
  - yarn test -- --ci --coverage
  - yarn run semantic-release
  
# jobs:
#   include:
#     - stage: release
#       # node_js: lts/*
#       script:
#         - yarn run semantic-release
        


  # release:
  #   <<: *defaults
  #   steps:
  #     - attach_workspace:
  #         at: ~/repo
  #     - checkout
  #     - run: npm run semantic-release

# workflows:
#   version: 2
#   build-and-release:
#     jobs:
#       - checkout_code
#       - build:
#           requires:
#             - checkout_code
#       - release:
#           requires:
#             - build
#           filters:
#             branches:
#               only: master
